<?php

namespace ForumBundle\Repository;

/**
 * ChangeParametersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChangeParametersRepository extends \Doctrine\ORM\EntityRepository
{
}
